var FACTS = [
  // Climate
  { category: 'climate', title: 'Climate change could be irreversible by 2030', text: 'According to a report from the UN Intergovernmental Panel on Climate Change (IPCC), urgent action is needed this decade to avoid the most catastrophic effects of global warming.' },
  { category: 'climate', title: 'The last decade was the hottest on record', text: '2011-2020 was the warmest decade since global record-keeping began in the 1880s, according to NASA and NOAA data.' },
  { category: 'climate', title: 'CO2 levels are higher than any point in 800,000 years', text: 'Ice core samples show atmospheric carbon dioxide concentration has not been this high in at least 800 millennia.' },
  { category: 'climate', title: 'Sea levels have risen about 21-24cm since 1880', text: 'Roughly a third of that rise has happened in just the last two and a half decades, as ice sheets melt faster.' },
  { category: 'climate', title: 'The Arctic is warming nearly four times faster than the rest of the planet', text: 'This phenomenon, called Arctic amplification, is driven largely by melting sea ice exposing darker ocean water that absorbs more heat.' },
  { category: 'climate', title: 'A single degree of warming reshapes entire ecosystems', text: 'Even a 1°C rise in global average temperature can shift the ranges of thousands of species and disrupt growing seasons worldwide.' },
  { category: 'climate', title: 'Cutting food waste is one of the top climate solutions', text: 'If food waste were a country, it would be the third-largest greenhouse gas emitter in the world, behind only the US and China.' },
  { category: 'climate', title: 'Extreme weather events have become 5x more frequent since the 1970s', text: 'Droughts, floods, and storms are now recorded roughly five times as often as fifty years ago, per the World Meteorological Organization.' },
  { category: 'climate', title: 'Glaciers are losing ice at an accelerating rate', text: 'The world’s glaciers lost over 9 trillion tonnes of ice between 1961 and 2016 — enough to cover the entire United States in over a metre of water.' },
  { category: 'climate', title: 'Renewable energy could meet 90% of the needed emissions cuts by 2050', text: 'The International Renewable Energy Agency estimates renewables, paired with efficiency, could deliver the bulk of the reductions needed to hit climate targets.' },
  { category: 'climate', title: 'Small islands are already losing land to rising seas', text: 'Several low-lying Pacific island nations have already lost measurable coastline, and some are planning eventual relocation.' },
  { category: 'climate', title: 'Trees planted today may not offset emissions for decades', text: 'A newly planted tree can take 10-20 years to sequester meaningful amounts of carbon, which is why protecting existing forests matters just as much as planting new ones.' },

  // Ocean
  { category: 'ocean', title: 'Our oceans are dying', text: 'Rising temperatures, acidification, and pollution are pushing marine ecosystems toward collapse faster than they can recover.' },
  { category: 'ocean', title: 'The ocean has absorbed over 90% of excess heat from global warming', text: 'Without the ocean acting as a heat sink, atmospheric warming would be far more severe than it already is.' },
  { category: 'ocean', title: 'Coral reefs support 25% of all marine species', text: 'Despite covering less than 1% of the ocean floor, reefs are among the most biodiverse ecosystems on Earth.' },
  { category: 'ocean', title: 'Half the world’s coral reefs have died since 1950', text: 'Warming seas and acidification have already destroyed roughly half of the reefs alive seventy years ago.' },
  { category: 'ocean', title: 'The ocean produces over half of the world’s oxygen', text: 'Marine phytoplankton generate more oxygen than all the world’s rainforests combined.' },
  { category: 'ocean', title: 'Overfishing has depleted a third of global fish stocks', text: 'The UN Food and Agriculture Organization estimates about 35% of assessed fish stocks are fished at unsustainable levels.' },
  { category: 'ocean', title: 'The deepest point in the ocean is deeper than Everest is tall', text: 'The Mariana Trench plunges to nearly 11,000 metres — over 2,000 metres deeper than Mount Everest is high.' },
  { category: 'ocean', title: 'Ocean acidity has increased by 30% since the industrial revolution', text: 'Absorbed CO2 is making seawater more acidic, making it harder for shellfish and corals to build their skeletons.' },
  { category: 'ocean', title: 'We’ve explored less than 20% of the ocean floor', text: 'More of the Moon’s surface has been mapped in detail than the floor of Earth’s own oceans.' },
  { category: 'ocean', title: 'Mangroves store up to 4x more carbon than rainforests, per hectare', text: 'These coastal forests are disappearing at a rate of about 1% a year, releasing stored carbon as they go.' },
  { category: 'ocean', title: 'A single whale can capture as much carbon as thousands of trees', text: 'Over their lifetime, great whales accumulate carbon in their bodies and, when they die naturally, sink it to the deep ocean floor.' },
  { category: 'ocean', title: 'Sea turtles have existed for over 100 million years', text: 'Nearly all seven species of sea turtle are now threatened, largely due to plastic pollution, bycatch, and habitat loss.' },

  // Forest
  { category: 'forest', title: 'Around 27,000 trees are cut down each day', text: 'Much of this is driven by the demand for toilet paper, packaging, and disposable products worldwide.' },
  { category: 'forest', title: 'The Amazon produces about 20% of the world’s oxygen', text: 'Often called the "lungs of the Earth," the Amazon rainforest plays an outsized role in the planet’s oxygen and carbon cycles.' },
  { category: 'forest', title: 'We lose a forest the size of a football pitch every second', text: 'Global tree cover loss, driven largely by agriculture and logging, continues at a staggering pace.' },
  { category: 'forest', title: 'Forests are home to 80% of the world’s terrestrial biodiversity', text: 'The vast majority of land-based species — plants, insects, birds, and mammals — depend on forest habitats.' },
  { category: 'forest', title: 'A single mature tree can absorb 22kg of CO2 a year', text: 'Over a 40-year lifespan, one tree can offset roughly a tonne of carbon dioxide.' },
  { category: 'forest', title: 'Old-growth forests store far more carbon than young plantations', text: 'A single old-growth tree can hold as much carbon as dozens of young replacement saplings combined.' },
  { category: 'forest', title: 'Reforestation is one of the cheapest ways to fight climate change', text: 'Researchers estimate restoring forests could capture roughly 25% of the carbon needed to keep warming in check, at relatively low cost.' },
  { category: 'forest', title: 'Bamboo grows up to 91cm in a single day', text: 'It’s one of the fastest-growing plants on Earth, making it a popular sustainable alternative to hardwood.' },
  { category: 'forest', title: 'Indigenous-managed forests have lower deforestation rates', text: 'Studies across the Amazon and beyond show forests under indigenous stewardship are often better protected than those without.' },
  { category: 'forest', title: 'Forest fires are becoming more frequent and more intense', text: 'Longer dry seasons and hotter temperatures have extended fire seasons by an average of 20% globally since 1979.' },
  { category: 'forest', title: 'One hectare of forest can absorb more CO2 than it releases', text: 'A healthy hectare of temperate forest can net-absorb around 2.6 tonnes of CO2 annually, acting as a genuine carbon sink.' },

  // Wildlife
  { category: 'wildlife', title: '78% of marine mammals are at risk of choking on plastic', text: 'Ingested plastic debris is one of the leading causes of injury and death among whales, dolphins, and seals.' },
  { category: 'wildlife', title: 'We’re losing species 1,000 times faster than the natural rate', text: 'Human activity has pushed the current extinction rate far beyond anything seen in the fossil record outside mass extinction events.' },
  { category: 'wildlife', title: 'One million species are at risk of extinction', text: 'A landmark UN biodiversity report found roughly a million plant and animal species now face extinction, many within decades.' },
  { category: 'wildlife', title: 'Bees pollinate about a third of the food we eat', text: 'Without pollinators like bees, many fruits, vegetables, and nuts would disappear from our diets entirely.' },
  { category: 'wildlife', title: 'Elephant populations have dropped by 60% in the last decade', text: 'Poaching for ivory and habitat loss have driven a steep decline in African elephant numbers.' },
  { category: 'wildlife', title: 'Tigers have lost 95% of their historical range', text: 'Fewer than 4,000 wild tigers remain today, confined to a fraction of the territory they once roamed.' },
  { category: 'wildlife', title: 'Coral bleaching events have tripled in frequency since the 1980s', text: 'Warmer oceans stress corals into expelling the algae that give them color and nutrients, often leading to die-off.' },
  { category: 'wildlife', title: 'Vultures can clean a carcass in under 20 minutes', text: 'These often-maligned scavengers prevent the spread of disease by rapidly removing decaying carcasses from ecosystems.' },
  { category: 'wildlife', title: 'Wildlife corridors help species survive habitat fragmentation', text: 'Connecting isolated habitats with protected corridors lets animals migrate, breed, and adapt as their environment changes.' },
  { category: 'wildlife', title: 'Monarch butterfly populations have declined by over 80%', text: 'Habitat loss along their migration route between North America and Mexico has devastated monarch numbers.' },
  { category: 'wildlife', title: 'Sharks are more at risk from us than we are from them', text: 'Humans kill roughly 100 million sharks a year, while sharks are involved in fewer than 100 human injuries.' },

  // Energy
  { category: 'energy', title: 'Solar power is now the cheapest electricity in history', text: 'In most parts of the world, new solar installations produce cheaper electricity than any fossil fuel option, including existing coal plants.' },
  { category: 'energy', title: 'Wind turbines can power a home for over a day with one rotation', text: 'A single rotation of a modern large wind turbine can generate enough electricity to power an average home for more than 24 hours.' },
  { category: 'energy', title: 'Renewables generated over 30% of global electricity in 2024', text: 'Solar and wind have grown from a niche source to a major pillar of the global power mix in under two decades.' },
  { category: 'energy', title: 'A single wind farm can offset the emissions of thousands of cars', text: 'Large offshore wind farms can generate enough clean electricity to offset the annual emissions of well over 100,000 vehicles.' },
  { category: 'energy', title: 'Standby power can account for up to 10% of household electricity use', text: 'Devices left plugged in on standby quietly draw power around the clock, adding up over a year.' },
  { category: 'energy', title: 'LED bulbs use up to 90% less energy than incandescent bulbs', text: 'Switching a home entirely to LED lighting can meaningfully cut both electricity bills and emissions.' },
  { category: 'energy', title: 'Geothermal energy taps heat that’s been stored for billions of years', text: 'Earth’s core has been radiating heat since the planet formed, offering a nearly limitless, always-on energy source.' },
  { category: 'energy', title: 'Battery storage costs have dropped by nearly 90% since 2010', text: 'Falling battery prices are making it increasingly practical to store solar and wind power for use after dark or on calm days.' },
  { category: 'energy', title: 'Electric vehicles produce zero tailpipe emissions', text: 'Even accounting for electricity generation, EVs typically produce far fewer lifetime emissions than comparable petrol vehicles.' },
  { category: 'energy', title: 'India is among the fastest-growing solar markets in the world', text: 'India has expanded its installed solar capacity more than tenfold over the past decade, driven by falling costs and ambitious targets.' },

  // Waste
  { category: 'waste', title: 'One supermarket uses 60 million paper/plastic bags each year', text: 'Multiply that across tens of thousands of stores worldwide, and single-use bags add up to an enormous waste stream.' },
  { category: 'waste', title: 'The average person generates over 2kg of waste a day', text: 'Global solid waste generation is expected to grow to 3.4 billion tonnes a year by 2050 without major changes in consumption.' },
  { category: 'waste', title: 'E-waste is the fastest-growing waste stream in the world', text: 'Discarded electronics contain valuable, recoverable metals, yet less than a quarter of e-waste is formally recycled.' },
  { category: 'waste', title: 'Food waste accounts for about 8% of global greenhouse gas emissions', text: 'Roughly a third of all food produced globally is lost or wasted, from farm to fork.' },
  { category: 'waste', title: 'Composting can cut household waste by up to 30%', text: 'Diverting food scraps and yard waste to compost keeps organic material out of landfills, where it produces methane.' },
  { category: 'waste', title: 'A glass bottle can take over 4,000 years to decompose', text: 'Unlike plastic, glass never fully breaks down — but it can be recycled indefinitely without losing quality.' },
  { category: 'waste', title: 'Only about 9% of all plastic ever made has been recycled', text: 'The vast majority of plastic waste ends up in landfills, incinerators, or the natural environment.' },
  { category: 'waste', title: 'Textile waste is growing as fast fashion accelerates', text: 'The equivalent of one garbage truck of clothes is landfilled or burned every second worldwide.' },
  { category: 'waste', title: 'Recycling one aluminium can saves enough energy to run a TV for 3 hours', text: 'Aluminium is one of the most efficient materials to recycle, using up to 95% less energy than producing it from raw ore.' },
  { category: 'waste', title: 'Landfills are a major source of methane emissions', text: 'Decomposing organic waste in landfills releases methane, a greenhouse gas more than 25 times more potent than CO2 over a century.' },
  { category: 'waste', title: 'Repairing electronics instead of replacing them cuts e-waste significantly', text: 'The "right to repair" movement argues that extending a device’s life by even a year meaningfully reduces its lifetime environmental footprint.' },

  // Water
  { category: 'water', title: 'Nearly 2 billion people lack access to safely managed drinking water', text: 'Water scarcity and contamination remain some of the most pressing global health and environmental challenges.' },
  { category: 'water', title: 'It takes about 2,700 litres of water to make one cotton t-shirt', text: 'From irrigation to dyeing and processing, textile production is one of the thirstiest industries in the world.' },
  { category: 'water', title: 'Agriculture accounts for roughly 70% of global freshwater use', text: 'Irrigation dwarfs household and industrial water consumption combined, making farming practices central to water conservation.' },
  { category: 'water', title: 'A leaking tap can waste over 11,000 litres of water a year', text: 'Even a slow drip adds up to thousands of litres of wasted water annually if left unrepaired.' },
  { category: 'water', title: 'Less than 1% of Earth’s water is accessible fresh water', text: 'Most of the planet’s water is saltwater or locked away in ice caps and glaciers, leaving a tiny fraction for drinking, farming, and industry.' },
  { category: 'water', title: 'Groundwater levels are dropping in many of the world’s major aquifers', text: 'Overextraction for agriculture and cities is depleting underground water reserves faster than they can naturally recharge.' },
  { category: 'water', title: 'A five-minute shower uses about 50-100 litres of water', text: 'Cutting shower time by even a couple of minutes can meaningfully reduce a household’s daily water footprint.' },
  { category: 'water', title: 'Wetlands filter pollutants and can improve water quality naturally', text: 'These ecosystems act as natural water treatment systems, trapping sediment and absorbing excess nutrients before they reach rivers and seas.' },
  { category: 'water', title: 'Rainwater harvesting can significantly cut a household’s water bill', text: 'Collecting and storing rainwater for irrigation and non-drinking uses reduces reliance on municipal or groundwater supplies.' },
  { category: 'water', title: 'Rivers move more freight, and more pollution, than most people realize', text: 'Ten rivers are estimated to carry the majority of plastic waste that reaches the ocean from land.' },

  // Air
  { category: 'air', title: 'Air pollution contributes to an estimated 7 million premature deaths a year', text: 'The World Health Organization ranks air pollution among the leading environmental risks to human health worldwide.' },
  { category: 'air', title: 'Indoor air can be more polluted than outdoor air', text: 'Household products, cooking fumes, and poor ventilation can cause indoor pollutant levels to exceed those outside.' },
  { category: 'air', title: 'Trees in cities can filter significant amounts of air pollution', text: 'Urban tree cover has been shown to measurably reduce particulate matter and improve local air quality.' },
  { category: 'air', title: 'Vehicle emissions are a leading source of urban air pollution', text: 'Transportation accounts for a large share of nitrogen oxide and particulate emissions in most major cities.' },
  { category: 'air', title: 'The ozone layer is slowly healing', text: 'Thanks to the Montreal Protocol banning ozone-depleting chemicals, the ozone hole is on track to fully recover by the 2060s.' },
  { category: 'air', title: 'Wildfire smoke can travel thousands of kilometres', text: 'Smoke from major wildfires has been tracked crossing entire oceans, affecting air quality far from the original blaze.' },
  { category: 'air', title: 'Cleaner cooking fuels could prevent millions of deaths', text: 'Around a third of the world still cooks with solid fuels like wood and coal, contributing heavily to indoor air pollution.' },
  { category: 'air', title: 'Electric public transport can cut a city’s emissions significantly', text: 'Cities that have electrified bus fleets have seen measurable drops in both emissions and local air pollution.' },
  { category: 'air', title: 'Houseplants have a modest but real effect on indoor air quality', text: 'While not a substitute for ventilation, certain plants can help filter small amounts of common indoor pollutants.' },

  // Food
  { category: 'food', title: 'A plant-based diet can cut an individual’s food-related emissions significantly', text: 'Studies estimate shifting away from meat and dairy can reduce a person’s dietary carbon footprint by up to 50%.' },
  { category: 'food', title: 'Livestock farming accounts for about 14.5% of global greenhouse gas emissions', text: 'This is roughly comparable to the emissions from the entire global transportation sector combined.' },
  { category: 'food', title: 'Local, seasonal produce typically has a smaller carbon footprint', text: 'Food transported long distances or grown out of season often requires more energy for shipping, refrigeration, and heating.' },
  { category: 'food', title: 'Nearly a third of food produced globally is never eaten', text: 'Losses happen at every stage — from farm harvesting to supermarket shelves to household fridges.' },
  { category: 'food', title: 'Urban farming is on the rise worldwide', text: 'Rooftop gardens and vertical farms are helping cities grow fresh produce closer to where people actually live.' },
  { category: 'food', title: 'Organic farming can improve soil health over time', text: 'Avoiding synthetic pesticides and fertilizers tends to support greater biodiversity in and around farmland.' },
  { category: 'food', title: 'A single almond can require over 4 litres of water to grow', text: 'Water-intensive crops grown in drought-prone regions raise real questions about sustainable agriculture.' },
  { category: 'food', title: 'Insects are a highly efficient source of protein', text: 'Farming insects for food requires a fraction of the land, water, and feed needed for conventional livestock.' },
  { category: 'food', title: 'Buying "ugly" produce helps reduce food waste', text: 'A significant share of edible fruits and vegetables is discarded at the farm level simply for not looking "market perfect."' },
  { category: 'food', title: 'Community gardens can strengthen both food security and local ecosystems', text: 'Shared growing spaces provide fresh produce while creating small pockets of urban biodiversity.' },

  // Biodiversity / general
  { category: 'wildlife', title: 'Biodiversity loss is accelerating faster than climate change in some regions', text: 'Habitat destruction, invasive species, and pollution are driving species loss even where climate impacts are still emerging.' },
  { category: 'wildlife', title: 'Protected areas now cover about 17% of the world’s land', text: 'International agreements aim to expand protected land and marine areas significantly this decade to safeguard biodiversity.' },
  { category: 'wildlife', title: 'Rewilding projects are bringing back lost predators and ecosystems', text: 'Reintroducing keystone species like wolves has been shown to restore balance across entire food webs, as seen in Yellowstone.' },
  { category: 'wildlife', title: 'Citizen science helps track biodiversity at a massive scale', text: 'Millions of everyday observations logged by hobbyists now feed into major global species-tracking databases.' },
  { category: 'wildlife', title: 'Fungi networks connect entire forests underground', text: 'Mycorrhizal fungi form vast underground networks that let trees share nutrients and even warning signals about pests.' },
  { category: 'climate', title: 'Permafrost thaw could release carbon locked away for millennia', text: 'Arctic permafrost holds an estimated 1,500 billion tonnes of carbon — nearly twice what’s currently in the atmosphere.' },
  { category: 'climate', title: 'Climate-driven migration is already reshaping communities', text: 'The World Bank estimates over 200 million people could be displaced within their own countries by climate impacts by 2050.' },
  { category: 'ocean', title: 'Kelp forests can grow up to 60cm in a single day', text: 'These fast-growing underwater forests store carbon, shelter marine life, and buffer coastlines from storm surges.' },
  { category: 'ocean', title: 'Plastic has been found in the deepest part of the ocean', text: 'A plastic bag was discovered nearly 11,000 metres down in the Mariana Trench — the deepest point on Earth.' },
  { category: 'forest', title: 'Peatlands store more carbon than all the world’s forests combined', text: 'Though they cover just 3% of Earth’s land, peatlands hold roughly twice as much carbon as all forest biomass.' },
  { category: 'forest', title: 'Urban tree canopy can lower city temperatures by several degrees', text: 'Shaded streets and parks can be noticeably cooler than paved, treeless areas during heatwaves.' },
  { category: 'energy', title: 'Hydropower is the largest source of renewable electricity worldwide', text: 'Dams and run-of-river systems together generate more renewable electricity globally than solar and wind combined.' },
  { category: 'energy', title: 'A rooftop solar system can pay for itself within several years', text: 'Falling panel costs and rising electricity prices have shortened the typical payback period for home solar considerably.' },
  { category: 'waste', title: 'Cigarette butts are the most littered item on Earth', text: 'Trillions of cigarette filters — made of slow-degrading plastic — are discarded into the environment every year.' },
  { category: 'waste', title: 'Reusable packaging schemes are gaining ground in retail', text: 'Several major retailers now offer refill and return schemes to cut down on single-use packaging waste.' },
  { category: 'water', title: 'Desalination is expanding as freshwater grows scarcer', text: 'Thousands of desalination plants now operate worldwide, though the process remains energy-intensive.' },
  { category: 'air', title: 'Public transport reduces per-person emissions dramatically', text: 'A full bus can take dozens of cars off the road, cutting both congestion and per-passenger emissions substantially.' },
  { category: 'food', title: 'Vertical farms use up to 95% less water than traditional agriculture', text: 'Closed-loop irrigation in indoor vertical farms recycles water that would otherwise be lost to evaporation and runoff.' },
];
